version: '3'
services:
  vnc_docker:
    image: vnc_docker:latest
    ports:
      - "5900:5900"
    container_name: vnc_docker
    networks:
      - default
    restart: unless-stopped
    volumes:
      - /home/homebank:/data:rw

  novnc:
    image: dougw/novnc
    environment:
      # Adjust to your screen size
      - REMOTE_HOST=192.168.1.10
      - REMOTE_PORT=5900
    ports:
      - "8555:8081"
    container_name: novnc
    networks:
      - default

